import { GetPlaylistRes } from "../types";

export const GET_PLAYLIST_RESPONSE: GetPlaylistRes = {
  title: "Backend Engineering (Intermediate)",
  videos: [
    "What is the TCP 3-Way Handshake and Why Backend Engineers should understand it",
    "Layer 4 vs Layer 7 Proxying In Details Explained with Examples",
    "Database Engines Crash Course (MyISAM, Aria, InnoDB, XtraDB, LevelDB & RocksDB)",
    "How HTTP/2 Works, Performance, Pros & Cons and More",
    "Load balancing in Layer 4 vs Layer 7 with HAPROXY Examples",
    "7 Tips to Optimize Your Backend API Without Caching",
    "Your Backend is Also a Frontend (Backend vs Frontend Engineering)",
    "Overengineering in Software",
    "NginX Crash Course (Layer 4 & Layer 7 Proxy, HTTPS, TLS 1.3, HTTP/2 & More)",
    "HAProxy Crash Course (TLS 1.3, HTTPS, HTTP/2 and more)",
    "What is a Virtual IP Address? How does it help with High-Availability",
    "Fail-over and High-Availability (Explained by Example)",
    "Active-Active vs Active-Passive Cluster to Achieve High Availability in Scaling Systems",
    "Connection Pooling in PostgresSQL with NodeJS (Performance Numbers)",
    "Asynchronous vs Multithreading and Multiprocessing Programming (The Main Difference)",
    "Horizontal vs Vertical Database Partitioning",
    "Database Partitioning Crash Course (with Postgres)",
    "Database Sharding Crash Course (with Postgres examples)",
    "Can you get Eventual Consistency in Relational Databases?",
    "How to Avoid Double Booking and Race Conditions in Online Web Applications",
    "RabbitMQ Crash Course",
    "Apache Kafka Crash Course",
    "Microservices Explained and their Pros & Cons",
    "When Designing a Backend System Minimize the “What If” Questions",
    "Building a Multi-player Game with WebSockets",
    "DevTools Waterfall Deep Dive - Diagnose Your Backend and Improve the Frontend User Experience",
    "SELECT COUNT(*) is Slow, Estimate it Instead (with Example in Node JS and Postgres)",
    "When to Build a Stateless vs Stateful Back-ends using the right protocols (UDP, HTTP, TCP, QUIC)",
    "Why you Shouldn't Implement Features Because They are Easy - Backend Engineering",
    "Index Scan vs Index Only Scan on Database Systems (with Postgres)",
    "SELECT COUNT (*) can impact your Backend Application Performance, here is why",
    "Combining Database Indexes for Better Performance in Your Backend Applications (with PostgreSQL)",
    "2 Hours RabbitMQ Course with NodeJS, Pros & Cons, Cloud RMQ, RMQ vs Kafka, RMQ in Wireshark & MORE!",
    "Uber’s new Backend Architecture for Processing Payments",
    "Traefik Crash Course (Without docker)",
    "Envoy Proxy Crash Course, Architecture, L7 & L4 Proxying, HTTP/2, Enabling TLS 1.2/1.3 and more",
    "don’t use “offset” in your SQL",
    "Is EventStoreDB the First Native gRPC Database?",
    "The 2021 Slack Outage - Detailed analysis of what happened to Slack on Jan 4th 2021",
    "How do i learn new tech as a software engineer",
    "Load Balance multiple RTMP Servers to Horizontally Scale Streaming (Node Media Server and HAProxy)",
    "CQRS is probably the cause of the Microservices madness",
    "How timeouts can make or break your Backend load balancers",
    "Watch out before Adding Indexes to Your Table, Your Database Optimizer Might not Use them",
    "Optimizing Communication and Networking in Database Systems - The Backend Engineering Show",
    "Long Polling and how it differs from Push, Poll and SSE - The Backend Engineering Show",
    "Explain Explained in PostgreSQL - How Databases Prepare Optimal Query Plans to Execute SQL",
    "B-tree vs B+ tree in Database Systems",
    "Should you go with an Optimistic or Pessimistic Concurrency Control Database?",
    "The Journey of an HTTP request to the Backend | Backend Engineering Show",
    "My thoughts on Low/no code | Backend Engineering Show",
    "Multi-tenancy architecture | The Backend Engineering Show",
    "First port your computer hits",
  ],
};
